[package]
name = "bfjoy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
build = "src/build.rs"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
include_dir = "0.7.2"

[dev-dependencies]
rand = "0.8.5"
rayon = "1.5.3"